### ISSUE TITLE
Eerste keer opstarten werkt niet.

### ISSUE THREAD

**Issue by zeusttu** [M-industries/AlanProjectTemplate#1]
Wanneer ik de Git-repo uitcheck en `start.sh` draai krijg ik bij de stap `Generating the GUI` de foutmelding `Cannot find model.lib`. Deze fout lijkt geintroduceerd in commit c18d79318a9787eec024e9294f969ed4e96ead1d. Wanner ik de commit daarvoor (c51dc9d313b0a37371788fe279fac51fb0c3b4f0) uitcheck doet `start.sh` het wel. Als ik daarna weer de nieuwste `master` uitcheck en nogmaals `start.sh` draai werkt het ook gewoon, dus het gaat alleen mis bij de eerste keer draaien (waarbij e.e.a. aan bouw- en initialisatie-werk plaatsvindt).

**Comment by braver** [comment]
Bedankt voor het melden! Gefixed in 22c7e101734b2cc06127cca318efa56006512ec9.
