### ISSUE TITLE
Visual Studio Code extension verwijzing klopt niet

### ISSUE THREAD

**Issue by LeonHagenaarsKeus** [M-industries/AlanProjectTemplate#4]
https://github.com/M-industries/AlanProjectTemplate/wiki/Syntax-Highlighting-etc verwijst nog naar 'Fabric' niet naar 'Alan'

**Comment by braver** [comment]
Inderdaad, over het hoofd gezien. Bijgewerkt nu, dit is de url: https://marketplace.visualstudio.com/items?itemName=M-industries.alan
