### ISSUE TITLE
Draft Memorandum of Understanding

### ISSUE THREAD

**Issue by vukovinski** [M-industries/AlanProjectTemplate#5]
Frankly, you win. Alan is wonderful.

I write to you out of my willingness to scuttle my early-stage [Regular7](https://regular7.github.io/) language to regain vested time and offer it to Alan.

Here is what I would like to see and work on:

- a type system which is globally and/or locally distributed + with a interactive proof checker
- marketing and developing Alan as a general human project description language
- an ecosystem of human project support tools (templates for starting film projects, publishing magazines, gathering consent in organizations, voting, etc.)

Of course, there is much to talk about and think through.

**Comment by braver** [comment]
@vukovinski Thanks for your message. Good to hear you like Alan! 💯  

If you want to contribute to the publicly available materials, we'd welcome pull requests on documentation. Also, if you have suggestions for things you think are missing in the platform als always welcome. If you want to be more involved, please get in touch via info@m-industries.com.
